# Generated by Django 3.2 on 2021-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempimg', models.ImageField(upload_to='tempimages/', verbose_name='')),
                ('temp', models.IntegerField()),
            ],
        ),
    ]
