# Generated by Django 3.2 on 2021-05-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimage',
            name='temp',
            field=models.FloatField(),
        ),
    ]
