# Generated by Django 3.2 on 2021-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_alter_tempimage_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimage',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
