# Generated by Django 3.2 on 2021-05-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_alter_tempimage_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='tempimage',
            name='temp',
            field=models.FloatField(blank=True, primary_key=True, serialize=False),
        ),
    ]
