# Generated by Django 3.2 on 2021-05-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('imagefile', models.ImageField(upload_to='images/', verbose_name='')),
                ('faceEmbedding', models.BinaryField()),
            ],
        ),
    ]
