# Generated by Django 3.1.7 on 2021-03-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('userImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
