# Generated by Django 3.1.7 on 2021-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='faceEmbedding',
            field=models.BinaryField(default=123),
            preserve_default=False,
        ),
    ]
