# Generated by Django 3.2 on 2021-05-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userImages', '0002_image_faceembedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='info',
            new_name='user',
        ),
    ]
